### ISSUE TITLE
Bug fix responsive design 

### ISSUE THREAD

**Issue by E1sh3r2** [E1sh3r2/E1sh3r2.github.io#17]
![Screenshot_20220524-132213.jpg](https://user-images.githubusercontent.com/77773301/170023538-18be088b-25f2-4a89-80d4-d733a773cf88.jpg)

Frage steht nicht mehr mittig auf dem Smartphone

**Comment by lachgas7778** [comment]
Ich habe die Frage extra ganz nach Unten gemacht. Der Grund dafür ist, dass die Finger die unteren Bereiche des Smartphones eher erreichen als die Oberen. Dadurch, dass die Frage angeklickt werden muss, um fortzufahren, habe ich den Margin-Wert der "Question" auf `margin-top: auto` gesetzt. Wenn das nicht passt, dann muss lediglich die CSS-Regel: `margin-bottom: auto` hinzugefügt werden.

**Comment by lachgas7778** [comment]
@E1sh3r2 Probier mal den ersten Kommentar mit dem Codeschnipsel aus:
https://dev.to/rachelg/a-javascript-fix-for-the-100vh-problem-on-mobile-screens-9im
